apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all-intra-namespace
  namespace: kubeflow-user-example-com
spec:
  # Seleziona l'embedding service
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: embedding-service
  action: ALLOW
  # Regola vuota = "Permetti tutto" (da chiunque, ovunque nel cluster)
  rules:
  - {}